/*Parser for test++ */


%token SEMI COLON LPAREN RPAREN LBRACE RBRACE LBRACKET RBRACKET TAG
%token PLUS MINUS TIMES DIVIDE MODULO ASSIGN NOT COMMA
%token EQ NEQ LT NEQ GT GEQ AND OR 
%token IF ELSE ELIF FOR WHILE CONT RETURN BOOL DEFINE DECLARE


%
%
%
%
%
%
%left PLUS DIVIDE
%left TIMES DIVIDE